-- Palvolve elements: element resolution for pairs, element colors for the FX
-- staging and the per-element adaptation stone lookup.
--
-- Element names follow EPalElementType (Normal, Fire, Water, Leaf,
-- Electricity, Ice, Earth, Dark, Dragon). Resolution prefers the runtime
-- database (patch-proof) and falls back to the baked table from
-- elements_static.lua (generated by tools/generate-data.mjs).

local Config = require("config")

local Elements = {}

local function Log(msg)
    print(string.format("[Palvolve] %s\n", msg))
end

Elements.BY_ENUM = {
    [1] = "Normal", [2] = "Fire", [3] = "Water", [4] = "Leaf",
    [5] = "Electricity", [6] = "Ice", [7] = "Earth", [8] = "Dark", [9] = "Dragon",
}

-- FX tint per element (FLinearColor tables; intensities above 1 glow in HDR)
Elements.COLORS = {
    Normal      = { R = 1.6, G = 1.6, B = 1.4, A = 1.0 },
    Fire        = { R = 2.2, G = 0.45, B = 0.10, A = 1.0 },
    Water       = { R = 0.25, G = 0.7, B = 2.2, A = 1.0 },
    Leaf        = { R = 0.35, G = 2.0, B = 0.45, A = 1.0 },
    Electricity = { R = 2.2, G = 1.9, B = 0.25, A = 1.0 },
    Ice         = { R = 0.6, G = 1.7, B = 2.2, A = 1.0 },
    Earth       = { R = 1.5, G = 0.95, B = 0.35, A = 1.0 },
    Dark        = { R = 1.1, G = 0.3, B = 1.9, A = 1.0 },
    Dragon      = { R = 0.7, G = 0.5, B = 2.2, A = 1.0 },
}

local staticTable = nil
local function staticElements(charId)
    if staticTable == nil then
        local ok, t = pcall(require, "elements_static")
        staticTable = (ok and type(t) == "table") and t or {}
    end
    return staticTable[charId]
end

-- Normalizes whatever the enum out-param marshals into (number, wrapper with
-- :get(), or an "EPalElementType::Fire" style string) to an element name.
local function toElementName(v)
    if v == nil then return nil end
    local n = tonumber(v)
    if not n and type(v) ~= "string" then
        pcall(function() n = tonumber(v:get()) end)
        if not n then pcall(function() v = v:ToString() end) end
    end
    if n then return Elements.BY_ENUM[n] end
    if type(v) == "string" then
        local name = v:match("([%w]+)$")
        if name and Elements.COLORS[name] then return name end
    end
    return nil
end

-- Runtime lookup via the character database; verified LAZILY on first real
-- use against the baked table (never during savegame load - the call can
-- crash natively while the world is still restoring).
local runtimeBroken = false
local runtimeVerified = false
local function runtimeElements(charId, worldCtx)
    if runtimeBroken then return nil end
    local result = nil
    pcall(function()
        local util = StaticFindObject("/Script/Pal.Default__PalUtility")
        if not (util and util:IsValid() and worldCtx and worldCtx:IsValid()) then return end
        local db = util:GetDatabaseCharacterParameter(worldCtx)
        if not (db and db:IsValid()) then return end
        local e1, e2 = db:GetElementType(FName(charId))
        local n1 = toElementName(e1)
        if n1 then
            result = { n1 }
            local n2 = toElementName(e2)
            if n2 then result[2] = n2 end
        end
    end)
    if result and not runtimeVerified then
        local st = staticElements(charId)
        if st and st[1] and result[1] ~= st[1] then
            runtimeBroken = true
            Log(string.format("Runtime element lookup mismatch (%s vs %s) - using baked table",
                result[1], st[1]))
            return nil
        end
        runtimeVerified = true
    end
    return result
end

-- { e1, e2? } for a character id, or nil
function Elements.of(charId, worldCtx)
    return runtimeElements(charId, worldCtx) or staticElements(charId)
end

-- Primary element name for a character id (FX coloring), or nil
function Elements.primary(charId, worldCtx)
    local e = Elements.of(charId, worldCtx)
    return e and e[1] or nil
end

function Elements.colorFor(elementName)
    return elementName and Elements.COLORS[elementName] or nil
end

-- The element an adaptation CHANGES INTO: the target element that the base
-- form does not have (CaptainPenguin Water/Ice -> _Black Water/Electricity
-- yields Electricity). Cosmetic variants with identical elements fall back
-- to the target's primary element. pair.element in the config overrides.
function Elements.adaptationElement(pair, worldCtx)
    if pair.element then return pair.element end
    local target = Elements.of(pair.to, worldCtx)
    if not target then
        Log(string.format("No element data for %s - configure `element` on the pair", pair.to))
        return nil
    end
    local base = Elements.of(pair.from, worldCtx)
    if base then
        local has = {}
        for _, e in ipairs(base) do has[e] = true end
        for _, e in ipairs(target) do
            if not has[e] then return e end
        end
    end
    return target[1]
end

return Elements
