-- GENERATED FILE - do not edit by hand. Regenerate: node tools/gen-worksuit.js
-- Vanilla per-species work-suitability base ranks (299 species).
-- Source: PalCalc db.json v27 (github.com/tylercamp/palcalc) (data updated 2026-07-28, mined 2026-07-30; 8/8 spot-checks vs paldb.cc)
-- Keys = internal CharacterID, exact-cased, no BOSS_ prefix (alphas share
-- the base form's ranks - the evolution.lua lookup strips the prefix).
return {
    ["Alpaca"] = { Farming = 2 },
    ["AmaterasuWolf"] = { Kindling = 3 },
    ["AmaterasuWolf_Dark"] = { Kindling = 4 },
    ["Anubis"] = { Handiwork = 6, Mining = 6, Transport = 4 },
    ["BadCatgirl"] = { Gathering = 4, Handiwork = 4, Lumbering = 2, Transport = 3 },
    ["Baphomet"] = { Handiwork = 2, Kindling = 3, Mining = 3, Transport = 2 },
    ["Baphomet_Dark"] = { Handiwork = 3, Mining = 4, Transport = 3 },
    ["Bastet"] = { Farming = 1, Gathering = 1 },
    ["Bastet_Ice"] = { Cooling = 1, Farming = 1 },
    ["BerryGoat"] = { Farming = 1, Planting = 2 },
    ["BerryGoat_Dark"] = { Farming = 1, Planting = 2 },
    ["BirdDragon"] = { Kindling = 2, Transport = 3 },
    ["BirdDragon_Ice"] = { Cooling = 2, Transport = 3 },
    ["BlackCentaur"] = { Lumbering = 6, Mining = 6 },
    ["BlackGriffon"] = { Gathering = 2 },
    ["BlackMetalDragon"] = { Handiwork = 3, Mining = 7 },
    ["BlackPuppy"] = { Gathering = 2 },
    ["BlackPuppy_Ice"] = { Cooling = 2, Gathering = 2 },
    ["BlueDragon"] = { Watering = 4 },
    ["BlueDragon_Ice"] = { Cooling = 4 },
    ["BluePlatypus"] = { Handiwork = 1, Transport = 1, Watering = 1 },
    ["BluePlatypus_Fire"] = { Handiwork = 1, Kindling = 2, Transport = 1, Watering = 2 },
    ["BlueSkyDragon"] = { Gathering = 5, Watering = 8 },
    ["BlueThunderHorse"] = { Electricity = 5 },
    ["BlueberryFairy"] = { Gathering = 2, Handiwork = 1, Medicine = 3, Planting = 3, Transport = 1 },
    ["Boar"] = { Mining = 1 },
    ["BrownRabbit"] = { Gathering = 4, Handiwork = 3, Mining = 2, Transport = 1 },
    ["CactusDoll"] = { Gathering = 3, Planting = 3, Transport = 1 },
    ["CactusDoll_Dark"] = { Gathering = 3, Planting = 3, Transport = 1 },
    ["CandleGhost"] = { Farming = 2, Gathering = 2, Handiwork = 3, Kindling = 3, Mining = 3 },
    ["CaptainPenguin"] = { Cooling = 2, Handiwork = 2, Mining = 3, Transport = 3, Watering = 2 },
    ["CaptainPenguin_Black"] = { Electricity = 3, Handiwork = 2, Mining = 3, Transport = 3, Watering = 2 },
    ["Carbunclo"] = { Gathering = 1, Handiwork = 1, Lumbering = 1, Medicine = 1, Planting = 1 },
    ["CatBat"] = { Gathering = 2, Mining = 3, Transport = 2 },
    ["CatMage"] = { Handiwork = 3, Medicine = 3, Transport = 2 },
    ["CatMage_Fire"] = { Handiwork = 3, Kindling = 3, Medicine = 3, Transport = 2 },
    ["CatVampire"] = { Medicine = 3 },
    ["ChickenPal"] = { Farming = 1, Gathering = 1 },
    ["ClioneTwins"] = { Handiwork = 2, Transport = 1, Watering = 1 },
    ["CloverFairy"] = { Gathering = 1, Planting = 1 },
    ["ClownRabbit"] = { Handiwork = 5, Kindling = 7, Medicine = 4, Transport = 2 },
    ["ColorfulBird"] = { Gathering = 1 },
    ["CowPal"] = { Farming = 2 },
    ["CubeTurtle"] = { Mining = 4 },
    ["CubeTurtle_Neutral"] = { Mining = 6 },
    ["CuteButterfly"] = { Gathering = 2, Medicine = 2, Planting = 2 },
    ["CuteFox"] = { Farming = 1, Gathering = 1 },
    ["CuteMole"] = { Handiwork = 1, Mining = 1, Transport = 1 },
    ["DandelionGirl"] = { Planting = 2, Transport = 2 },
    ["DarkAlien"] = { Lumbering = 3, Transport = 2 },
    ["DarkCrow"] = { Farming = 1, Lumbering = 2 },
    ["DarkFlameFox"] = { Handiwork = 5, Kindling = 4, Medicine = 3, Transport = 2 },
    ["DarkMechaDragon"] = { Gathering = 2 },
    ["DarkScorpion"] = { Lumbering = 3, Mining = 5 },
    ["DarkScorpion_Ground"] = { Lumbering = 3, Mining = 6 },
    ["Deer"] = { Lumbering = 2 },
    ["Deer_Ground"] = { Lumbering = 2 },
    ["DomeArmorDragon"] = { Mining = 8 },
    ["DreamDemon"] = { Gathering = 1, Handiwork = 1, Transport = 1 },
    ["DrillGame"] = { Mining = 4 },
    ["Eagle"] = { Gathering = 2 },
    ["ElecCat"] = { Electricity = 1, Farming = 1, Handiwork = 1, Transport = 1 },
    ["ElecLizard"] = { Electricity = 3 },
    ["ElecPanda"] = { Electricity = 5, Handiwork = 4, Lumbering = 3, Transport = 5 },
    ["ElecPomeranian"] = { Electricity = 2, Transport = 1 },
    ["ElecSnail"] = { Electricity = 4 },
    ["ElecSnail_Ground"] = { Electricity = 4 },
    ["FairyDragon"] = { Lumbering = 3 },
    ["FairyDragon_Water"] = { Lumbering = 3, Watering = 4 },
    ["FeatherOstrich"] = { Gathering = 2 },
    ["FengyunDeeper"] = { Lumbering = 3 },
    ["FengyunDeeper_Electric"] = { Electricity = 5, Lumbering = 4 },
    ["FireKirin"] = { Kindling = 4, Lumbering = 2 },
    ["FireKirin_Dark"] = { Kindling = 4, Lumbering = 3 },
    ["FlameBambi"] = { Farming = 1, Kindling = 1 },
    ["FlameBuffalo"] = { Kindling = 3, Lumbering = 2 },
    ["FlowerDinosaur"] = { Lumbering = 3, Planting = 3 },
    ["FlowerDinosaur_Electric"] = { Electricity = 3, Lumbering = 4 },
    ["FlowerDoll"] = { Gathering = 3, Handiwork = 3, Medicine = 4, Planting = 4, Transport = 2 },
    ["FlowerDoll_Fire"] = { Gathering = 3, Handiwork = 3, Kindling = 4, Medicine = 4, Transport = 2 },
    ["FlowerPrince"] = { Gathering = 5, Handiwork = 6, Medicine = 6, Planting = 8, Transport = 3 },
    ["FlowerRabbit"] = { Gathering = 2, Handiwork = 2, Medicine = 1, Planting = 2, Transport = 1 },
    ["FluffyBird"] = { Cooling = 2, Transport = 1 },
    ["FlyingManta"] = { Transport = 1, Watering = 1 },
    ["FlyingManta_Thunder"] = { Electricity = 2, Transport = 1, Watering = 1 },
    ["FoxExorcist"] = { Handiwork = 6, Kindling = 7, Transport = 2 },
    ["FoxMage"] = { Handiwork = 3, Kindling = 3, Transport = 2 },
    ["FoxMage_Dark"] = { Handiwork = 4, Kindling = 4, Transport = 2 },
    ["Ganesha"] = { Watering = 1 },
    ["Garm"] = { Gathering = 1 },
    ["GhostAnglerfish"] = { Transport = 2, Watering = 5 },
    ["GhostAnglerfish_Fire"] = { Kindling = 5, Transport = 2, Watering = 5 },
    ["GhostBeast"] = { Gathering = 4, Mining = 4 },
    ["GhostBlackCat"] = { Handiwork = 2, Lumbering = 1, Medicine = 1, Transport = 1 },
    ["GhostDragon"] = { Transport = 6 },
    ["GhostDragon_Fire"] = { Kindling = 6, Transport = 6 },
    ["GhostRabbit"] = { Handiwork = 4, Transport = 2 },
    ["GhostRabbit_Grass"] = { Handiwork = 4, Planting = 3, Transport = 2 },
    ["GoldenHorse"] = { Gathering = 5 },
    ["Gorilla"] = { Handiwork = 2, Lumbering = 3, Transport = 3 },
    ["Gorilla_Ground"] = { Handiwork = 2, Mining = 3, Transport = 3 },
    ["GrassGolem"] = { Gathering = 3, Lumbering = 5, Mining = 6, Planting = 3, Transport = 6 },
    ["GrassGolem_Dark"] = { Gathering = 3, Lumbering = 5, Mining = 6, Planting = 3, Transport = 6 },
    ["GrassMammoth"] = { Lumbering = 4, Mining = 4, Planting = 4 },
    ["GrassMammoth_Ice"] = { Cooling = 5, Lumbering = 5, Mining = 4 },
    ["GrassMinotaur"] = { Gathering = 2, Lumbering = 3, Mining = 2, Planting = 3, Transport = 3 },
    ["GrassMinotaur_Ice"] = { Cooling = 5, Lumbering = 3, Mining = 3, Transport = 3 },
    ["GrassPanda"] = { Handiwork = 2, Lumbering = 4, Planting = 3, Transport = 4 },
    ["GrassPanda_Electric"] = { Electricity = 4, Handiwork = 3, Lumbering = 4, Transport = 4 },
    ["GrassRabbitMan"] = { Gathering = 5, Handiwork = 5, Lumbering = 3, Planting = 4, Transport = 3 },
    ["GrimGirl"] = { Handiwork = 6, Lumbering = 3, Medicine = 5, Transport = 2 },
    ["GuardianDog"] = { Gathering = 2 },
    ["HadesBird"] = { Transport = 4 },
    ["HadesBird_Electric"] = { Electricity = 4, Transport = 5 },
    ["HawkBird"] = { Gathering = 2 },
    ["Hedgehog"] = { Electricity = 1 },
    ["Hedgehog_Ice"] = { Cooling = 1 },
    ["HerculesBeetle"] = { Handiwork = 3, Lumbering = 4, Planting = 3, Transport = 5 },
    ["HerculesBeetle_Ground"] = { Handiwork = 2, Mining = 5, Transport = 5 },
    ["HoodGhost"] = { Handiwork = 1, Transport = 1 },
    ["Horus"] = { Kindling = 6, Transport = 3 },
    ["Horus_Water"] = { Transport = 5, Watering = 6 },
    ["IceCrocodile"] = { Cooling = 3, Transport = 1, Watering = 2 },
    ["IceDeer"] = { Cooling = 3, Lumbering = 3 },
    ["IceFox"] = { Cooling = 4, Farming = 3 },
    ["IceHorse"] = { Cooling = 7 },
    ["IceHorse_Dark"] = { Gathering = 7 },
    ["IceNarwhal"] = { Cooling = 6, Watering = 5 },
    ["IceNarwhal_Fire"] = { Cooling = 6, Kindling = 5 },
    ["IceSeal"] = { Cooling = 4, Watering = 3 },
    ["IceSeal_Ground"] = { Cooling = 4, Mining = 4 },
    ["IceWitch"] = { Cooling = 5, Handiwork = 5, Medicine = 4, Transport = 2 },
    ["JellyfishFairy"] = { Handiwork = 1, Transport = 1, Watering = 2 },
    ["JellyfishGhost"] = { Handiwork = 1, Medicine = 1, Transport = 1, Watering = 2 },
    ["JetDragon"] = { Gathering = 8 },
    ["KabukiMan"] = { Gathering = 5, Handiwork = 6, Kindling = 8, Transport = 5 },
    ["Kelpie"] = { Farming = 1, Watering = 1 },
    ["Kelpie_Fire"] = { Farming = 1, Kindling = 1 },
    ["KendoFrog"] = { Gathering = 1, Handiwork = 1, Transport = 1, Watering = 1 },
    ["KendoFrog_Dark"] = { Gathering = 1, Handiwork = 2, Transport = 1, Watering = 1 },
    ["KingAlpaca"] = { Gathering = 2 },
    ["KingAlpaca_Ice"] = { Cooling = 4, Gathering = 2 },
    ["KingBahamut"] = { Kindling = 6, Mining = 7 },
    ["KingBahamut_Dragon"] = { Kindling = 6, Mining = 7 },
    ["KingSunfish"] = { Watering = 4 },
    ["KingSunfish_Thunder"] = { Electricity = 6, Watering = 4 },
    ["KingWhale"] = {  },
    ["Kirin"] = { Electricity = 3, Lumbering = 1 },
    ["Kirin_Ice"] = { Cooling = 6, Lumbering = 3 },
    ["Kitsunebi"] = { Kindling = 1 },
    ["Kitsunebi_Ice"] = { Cooling = 2 },
    ["LanternButler"] = { Handiwork = 4, Kindling = 4, Medicine = 4 },
    ["LavaGirl"] = { Farming = 1, Handiwork = 1, Kindling = 1, Transport = 1 },
    ["LazyCatfish"] = { Farming = 1, Mining = 2, Transport = 1, Watering = 2 },
    ["LazyCatfish_Gold"] = { Farming = 4, Mining = 2, Transport = 1, Watering = 2 },
    ["LazyDragon"] = { Transport = 3, Watering = 3 },
    ["LazyDragon_Electric"] = { Electricity = 4, Transport = 3 },
    ["LeafMomonga"] = { Gathering = 1, Planting = 1, Transport = 1 },
    ["LeafPrincess"] = { Gathering = 2, Handiwork = 3, Medicine = 3, Planting = 3 },
    ["LegendDeer"] = { Gathering = 7, Lumbering = 7 },
    ["LilyQueen"] = { Gathering = 6, Handiwork = 5, Medicine = 5, Planting = 7 },
    ["LilyQueen_Dark"] = { Gathering = 6, Handiwork = 5, Medicine = 7 },
    ["LittleBriarRose"] = { Gathering = 2, Handiwork = 2, Medicine = 2, Planting = 2, Transport = 1 },
    ["LizardMan"] = { Gathering = 1, Handiwork = 2, Transport = 1 },
    ["LizardMan_Fire"] = { Gathering = 1, Handiwork = 2, Kindling = 2, Transport = 1 },
    ["LongCat"] = { Gathering = 2 },
    ["LotusDragon"] = { Planting = 7, Watering = 5 },
    ["Manticore"] = { Kindling = 5, Lumbering = 3 },
    ["Manticore_Dark"] = { Kindling = 5, Lumbering = 3 },
    ["MimicDog"] = { Gathering = 1, Transport = 2 },
    ["Monkey"] = { Gathering = 1, Handiwork = 1, Lumbering = 1, Planting = 1, Transport = 1 },
    ["Monkey_Fire"] = { Handiwork = 1, Kindling = 1, Lumbering = 1, Transport = 1 },
    ["MonochromeQueen"] = { Gathering = 4, Handiwork = 8, Transport = 2 },
    ["MoonChild"] = { Handiwork = 6, Medicine = 6, Transport = 1 },
    ["MoonQueen"] = { Handiwork = 7, Medicine = 6, Transport = 3 },
    ["MopBaby"] = { Cooling = 1, Gathering = 1 },
    ["MopKing"] = { Cooling = 3, Gathering = 2 },
    ["Mothman"] = { Gathering = 4, Handiwork = 6, Medicine = 8, Planting = 6, Transport = 2 },
    ["MummyPal"] = { Handiwork = 5, Medicine = 4, Transport = 2 },
    ["MushroomDragon"] = { Farming = 3, Gathering = 3, Handiwork = 2, Lumbering = 2, Planting = 3 },
    ["MushroomDragon_Dark"] = { Gathering = 3, Handiwork = 3, Lumbering = 2, Planting = 3 },
    ["MushroomLady"] = { Gathering = 4, Handiwork = 4, Medicine = 6, Planting = 6 },
    ["Mutant"] = { Gathering = 2, Handiwork = 4, Transport = 2 },
    ["MysteryMask"] = { Gathering = 5 },
    ["NaughtyCat"] = { Gathering = 3 },
    ["NegativeKoala"] = { Farming = 1, Handiwork = 1, Mining = 1, Transport = 1 },
    ["NegativeOctopus"] = { Gathering = 1, Transport = 2, Watering = 1 },
    ["NegativeOctopus_Neutral"] = { Gathering = 1, Transport = 2, Watering = 1 },
    ["NightBlueHorse"] = { Gathering = 5 },
    ["NightBlueHorse_Neutral"] = { Gathering = 7 },
    ["NightFox"] = { Gathering = 1 },
    ["NightLady"] = { Handiwork = 5, Medicine = 5, Transport = 4 },
    ["NightLady_Dark"] = { Handiwork = 6, Medicine = 7, Transport = 4 },
    ["OctopusGirl"] = { Handiwork = 2, Transport = 2, Watering = 2 },
    ["OctopusGirl_Neutral"] = { Handiwork = 2, Transport = 2, Watering = 2 },
    ["OniGhostGirl"] = { Handiwork = 3, Medicine = 4, Transport = 2 },
    ["PandaGirl"] = { Gathering = 3, Handiwork = 3, Planting = 3, Transport = 2 },
    ["Penguin"] = { Cooling = 1, Handiwork = 1, Transport = 1, Watering = 1 },
    ["Penguin_Electric"] = { Electricity = 2, Handiwork = 1, Transport = 1, Watering = 1 },
    ["PinkCat"] = { Gathering = 1, Handiwork = 1, Mining = 1, Transport = 1 },
    ["PinkLizard"] = { Handiwork = 3, Medicine = 3, Mining = 2, Transport = 2 },
    ["PinkRabbit"] = { Gathering = 1, Handiwork = 1, Transport = 1 },
    ["PinkRabbit_Grass"] = { Gathering = 2, Handiwork = 2, Planting = 2, Transport = 1 },
    ["PlantSlime"] = { Planting = 1 },
    ["PlantSlime_Flower"] = { Planting = 1 },
    ["Plesiosaur"] = { Gathering = 5, Mining = 3, Planting = 5 },
    ["PoseidonOrca"] = { Watering = 7 },
    ["PurpleSpider"] = { Gathering = 3, Handiwork = 3, Medicine = 2, Transport = 2 },
    ["QueenBee"] = { Gathering = 4, Handiwork = 4, Lumbering = 3, Medicine = 4, Planting = 4 },
    ["RaijinDaughter"] = { Electricity = 3, Handiwork = 2, Transport = 2 },
    ["RaijinDaughter_Water"] = { Electricity = 1, Handiwork = 1, Medicine = 1, Transport = 2 },
    ["RedArmorBird"] = { Kindling = 4, Transport = 5 },
    ["RedFlowerBird"] = { Gathering = 5, Planting = 5 },
    ["RobinHood"] = { Gathering = 3, Handiwork = 3, Lumbering = 2, Medicine = 1, Planting = 2, Transport = 2 },
    ["RobinHood_Ground"] = { Gathering = 3, Handiwork = 3, Lumbering = 2, Medicine = 2, Transport = 2 },
    ["RockBeast"] = { Mining = 5 },
    ["RockBeast_Ice"] = { Cooling = 6, Mining = 5 },
    ["Ronin"] = { Gathering = 1, Handiwork = 2, Kindling = 2, Lumbering = 3, Transport = 2 },
    ["Ronin_Dark"] = { Gathering = 1, Handiwork = 2, Kindling = 2, Lumbering = 5, Transport = 2 },
    ["SaintCentaur"] = { Lumbering = 6, Mining = 6 },
    ["SakuraSaurus"] = { Planting = 5 },
    ["SakuraSaurus_Water"] = { Watering = 5 },
    ["SamuraiDog"] = { Gathering = 1, Lumbering = 1, Transport = 1 },
    ["ScorpionMan"] = { Gathering = 2, Lumbering = 4, Medicine = 2 },
    ["ScorpionMan_Electric"] = { Electricity = 3, Gathering = 2, Lumbering = 4, Medicine = 2 },
    ["Sekhmet"] = { Handiwork = 6, Mining = 3, Transport = 2 },
    ["Serpent"] = { Farming = 2, Watering = 3 },
    ["Serpent_Ground"] = { Gathering = 3 },
    ["SharkKid"] = { Handiwork = 2, Transport = 1, Watering = 2 },
    ["SharkKid_Fire"] = { Handiwork = 2, Kindling = 2, Transport = 1 },
    ["SheepBall"] = { Farming = 1, Handiwork = 1, Transport = 1 },
    ["SifuDog"] = { Gathering = 3, Handiwork = 4, Lumbering = 3, Medicine = 2, Transport = 3 },
    ["SkyDragon"] = { Gathering = 3, Handiwork = 2, Mining = 4, Transport = 5 },
    ["SkyDragon_Grass"] = { Gathering = 4, Handiwork = 2, Mining = 3, Planting = 5, Transport = 4 },
    ["SleeveRabbit"] = { Gathering = 5, Handiwork = 6 },
    ["SmallArmadillo"] = { Mining = 1 },
    ["SmallYeti"] = { Cooling = 3, Handiwork = 2, Mining = 3, Transport = 2 },
    ["SnakeGirl"] = { Gathering = 6, Handiwork = 6, Medicine = 5, Transport = 2 },
    ["SnowPeafowl"] = { Cooling = 4, Gathering = 2 },
    ["SnowTigerBeastman"] = { Cooling = 8, Lumbering = 6, Mining = 5 },
    ["SoldierBee"] = { Farming = 3, Gathering = 3, Handiwork = 2, Lumbering = 2, Medicine = 2, Planting = 2, Transport = 2 },
    ["StuffedShark"] = { Transport = 1, Watering = 2 },
    ["StuffedShark_Fire"] = { Kindling = 2, Transport = 1, Watering = 2 },
    ["SumoDog"] = { Mining = 4, Transport = 3 },
    ["Suzaku"] = { Kindling = 5 },
    ["Suzaku_Water"] = { Watering = 6 },
    ["SweetsSheep"] = { Farming = 1 },
    ["SweetsSheep_Ground"] = { Farming = 1 },
    ["SwordCutlassfish"] = { Gathering = 1, Lumbering = 4, Watering = 4 },
    ["SwordCutlassfish_Fire"] = { Gathering = 2, Kindling = 3, Lumbering = 3, Watering = 2 },
    ["TentacleTurtle"] = { Mining = 1, Transport = 1, Watering = 2 },
    ["TentacleTurtle_Ground"] = { Mining = 3, Transport = 1, Watering = 2 },
    ["ThiefBird"] = { Gathering = 5, Transport = 5 },
    ["ThunderBird"] = { Electricity = 4, Gathering = 2, Transport = 5 },
    ["ThunderBird_Ice"] = { Cooling = 5, Gathering = 2, Transport = 5 },
    ["ThunderDog"] = { Electricity = 4 },
    ["ThunderDog_Ice"] = { Cooling = 3 },
    ["ThunderDragonMan"] = { Electricity = 8, Handiwork = 3, Transport = 4 },
    ["ThunderFluffyBird"] = { Electricity = 6, Gathering = 3, Transport = 3 },
    ["TropicalOstrich"] = { Gathering = 4, Mining = 5, Planting = 4 },
    ["Umihebi"] = { Watering = 7 },
    ["Umihebi_Fire"] = { Kindling = 7 },
    ["VenusFlytrap"] = { Gathering = 4, Handiwork = 4, Planting = 6, Transport = 2 },
    ["VioletFairy"] = { Farming = 2, Gathering = 3, Handiwork = 3, Medicine = 3, Planting = 3, Transport = 2 },
    ["VolcanicMonster"] = { Kindling = 5, Mining = 5 },
    ["VolcanicMonster_Ice"] = { Cooling = 5, Mining = 5 },
    ["VolcanoDragon"] = { Kindling = 5, Mining = 5 },
    ["VolcanoDragon_Ice"] = { Cooling = 5, Mining = 5 },
    ["WeaselDragon"] = { Cooling = 2, Gathering = 1 },
    ["WeaselDragon_Fire"] = { Gathering = 3, Kindling = 4 },
    ["Werewolf"] = { Handiwork = 2 },
    ["Werewolf_Ice"] = { Cooling = 4, Handiwork = 4 },
    ["WhiteAlienDragon"] = { Mining = 4 },
    ["WhiteDeer"] = { Gathering = 4, Lumbering = 7 },
    ["WhiteDeer_Dark"] = { Gathering = 4, Lumbering = 8 },
    ["WhiteMoth"] = { Cooling = 3, Farming = 3, Medicine = 3 },
    ["WhiteMoth_Neutral"] = { Farming = 4, Medicine = 3 },
    ["WhiteShieldDragon"] = { Lumbering = 6 },
    ["WhiteTiger"] = { Cooling = 4, Handiwork = 3, Lumbering = 4, Transport = 4 },
    ["WhiteTiger_Ground"] = { Handiwork = 2, Lumbering = 6, Mining = 5, Transport = 4 },
    ["WindChimes"] = { Gathering = 1, Handiwork = 1, Transport = 2 },
    ["WindChimes_Ice"] = { Cooling = 2, Gathering = 2, Handiwork = 3, Transport = 3 },
    ["WingGolem"] = { Gathering = 4, Mining = 7, Transport = 7 },
    ["WingGolem_Fire"] = { Kindling = 5, Mining = 7, Transport = 7 },
    ["WizardOwl"] = { Gathering = 1 },
    ["WoolFox"] = { Farming = 2, Gathering = 1 },
    ["YakushimaBoss001"] = { Transport = 4 },
    ["YakushimaBoss001_Small"] = { Transport = 1 },
    ["YakushimaMonster001"] = { Transport = 1 },
    ["YakushimaMonster001_Blue"] = { Transport = 1 },
    ["YakushimaMonster001_Pink"] = { Transport = 1 },
    ["YakushimaMonster001_Purple"] = { Transport = 1 },
    ["YakushimaMonster001_Rainbow"] = { Transport = 1 },
    ["YakushimaMonster001_Red"] = { Transport = 1 },
    ["YakushimaMonster002"] = { Lumbering = 1 },
    ["YakushimaMonster003"] = { Gathering = 1 },
    ["YakushimaMonster003_Purple"] = { Gathering = 1 },
    ["Yeti"] = { Cooling = 5, Handiwork = 3, Lumbering = 5, Transport = 6 },
    ["Yeti_Grass"] = { Handiwork = 3, Lumbering = 5, Planting = 3, Transport = 6 },
}
