// Dev-side generator: bakes resolved DataTable JSONs (UAssetGUI tojson with the
// registered usmap, see Workspace/docs/EXTRACTION.md) into Lua fallback tables
// and the fruit->element mapping used to generate essence recipes.
//
// Usage: node tools/generate-data.mjs
// Inputs:  Workspace/extracted/resolved/DT_*.json
// Outputs: scripts/elements_static.lua   (CharacterID -> element name)
//          scripts/drops_static.lua      (CharacterID -> level bands -> drops)
//          tools/out/fruit_elements.json (SkillCard_* -> element name)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const RESOLVED = join(HERE, "..", "..", "Workspace", "extracted", "resolved");
const SCRIPTS = join(HERE, "..", "scripts");
const OUT = join(HERE, "out");
mkdirSync(OUT, { recursive: true });

function loadRows(file) {
    const j = JSON.parse(readFileSync(join(RESOLVED, file), "utf8"));
    const table = j.Exports.find((e) => (e["$type"] || "").includes("DataTableExport"));
    if (!table) throw new Error(`${file}: no DataTableExport`);
    return table.Table.Data;
}

// Property list -> plain object; enum values may carry an "EEnum::" prefix
function props(row) {
    const o = {};
    for (const p of row.Value) {
        let v = p.Value;
        if (typeof v === "string" && v.includes("::")) v = v.split("::").pop();
        o[p.Name] = v;
    }
    return o;
}

const skipPrefixes = ["BOSS_", "GYM_", "RAID_", "PREDATOR_", "SUMMON_", "Test"];
const skip = (name) => skipPrefixes.some((p) => name.startsWith(p));

// ---------------------------------------------------------------- elements
{
    const rows = loadRows("DT_PalMonsterParameter.json");
    const lines = [];
    for (const row of rows) {
        if (skip(row.Name)) continue;
        const p = props(row);
        const e1 = p.ElementType1;
        if (!e1 || e1 === "None") continue;
        const e2 = p.ElementType2 && p.ElementType2 !== "None" ? p.ElementType2 : null;
        const value = e2
            ? `{ ${JSON.stringify(e1)}, ${JSON.stringify(e2)} }`
            : `{ ${JSON.stringify(e1)} }`;
        lines.push(`    [${JSON.stringify(row.Name)}] = ${value},`);
    }
    lines.sort();
    writeFileSync(
        join(SCRIPTS, "elements_static.lua"),
        "-- GENERATED by tools/generate-data.mjs from DT_PalMonsterParameter\n" +
            "-- (buildid 24088745) - do not edit by hand. CharacterID -> { element1, element2? }.\n" +
            "return {\n" + lines.join("\n") + "\n}\n"
    );
    console.log(`elements_static.lua: ${lines.length} species`);
}

// ---------------------------------------------------------------- drops
{
    // known item ids for validation (drop rows occasionally carry ids that
    // are not craft/inventory items; those would make costs unpayable)
    const knownItems = new Set(loadRows("DT_ItemDataTable.json").map((r) => r.Name));
    const unknownSeen = new Set();
    // composite table: parent (_Common) first, self overrides
    const byKey = new Map();
    for (const file of ["DT_PalDropItem_Common.json", "DT_PalDropItem.json"]) {
        for (const row of loadRows(file)) byKey.set(row.Name, row);
    }
    // group by CharacterID field (row names carry band suffixes like 000/070)
    const bySpecies = new Map();
    for (const [name, row] of byKey) {
        if (skip(name)) continue;
        const p = props(row);
        const charId = p.CharacterID;
        if (!charId || charId === "None") continue;
        const drops = [];
        for (let i = 1; i <= 10; i++) {
            const id = p[`ItemId${i}`];
            if (!id || id === "None") continue;
            if (!knownItems.has(id)) {
                unknownSeen.add(id);
                continue;
            }
            drops.push({
                id,
                rate: Number(p[`Rate${i}`] ?? 0),
                min: Number(p[`min${i}`] ?? p[`Min${i}`] ?? 0),
                max: Number(p[`Max${i}`] ?? 0),
            });
        }
        if (drops.length === 0) continue;
        if (!bySpecies.has(charId)) bySpecies.set(charId, []);
        bySpecies.get(charId).push({ level: Number(p.Level ?? 0), drops });
    }
    const lines = [];
    for (const [charId, bands] of [...bySpecies].sort((a, b) => a[0].localeCompare(b[0]))) {
        bands.sort((a, b) => a.level - b.level);
        const bandStr = bands
            .map(
                (b) =>
                    `{ level = ${b.level}, drops = { ` +
                    b.drops
                        .map(
                            (d) =>
                                `{ id = ${JSON.stringify(d.id)}, rate = ${d.rate}, min = ${d.min}, max = ${d.max} }`
                        )
                        .join(", ") +
                    ` } }`
            )
            .join(", ");
        lines.push(`    [${JSON.stringify(charId)}] = { ${bandStr} },`);
    }
    writeFileSync(
        join(SCRIPTS, "drops_static.lua"),
        "-- GENERATED by tools/generate-data.mjs from DT_PalDropItem(_Common)\n" +
            "-- (buildid 24088745) - do not edit by hand. Boss/raid variants excluded.\n" +
            "-- CharacterID -> ascending level bands -> drop slots.\n" +
            "return {\n" + lines.join("\n") + "\n}\n"
    );
    console.log(`drops_static.lua: ${lines.length} species`);
}

// ---------------------------------------------------------------- fruits
{
    const wazaElement = new Map();
    for (const file of ["DT_WazaDataTable_Common.json", "DT_WazaDataTable.json"]) {
        for (const row of loadRows(file)) {
            const p = props(row);
            if (p.WazaType) wazaElement.set(p.WazaType, p.Element);
        }
    }
    const fruits = {};
    const missing = [];
    for (const row of loadRows("DT_ItemDataTable.json")) {
        if (!row.Name.startsWith("SkillCard_")) continue;
        const p = props(row);
        const waza = p.WazaID;
        const el = wazaElement.get(waza);
        if (el && el !== "None") fruits[row.Name] = el;
        else missing.push(`${row.Name} (WazaID=${waza})`);
    }
    writeFileSync(join(OUT, "fruit_elements.json"), JSON.stringify(fruits, null, 2));
    console.log(`fruit_elements.json: ${Object.keys(fruits).length} fruits`);
    if (missing.length) console.log(`UNRESOLVED: ${missing.join(", ")}`);
}
